---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@fbeb9d9cfe38488df1ccfbe220179aa9390fb074
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  build-darwin:
    needs: build-linux
    runs-on: macos-latest
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@fbeb9d9cfe38488df1ccfbe220179aa9390fb074
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  build-linux-arm:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@fbeb9d9cfe38488df1ccfbe220179aa9390fb074
        with:
          extra-platforms: aarch64-linux
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
